import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import morgan from 'morgan';
import dotenv from 'dotenv';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import nodemailer from 'nodemailer';
import path from 'path';
import fs from 'fs';
import {fileURLToPath} from 'url';
dotenv.config();
const app=express();app.use(cors({origin:process.env.CLIENT_URL||true}));app.use(express.json({limit:'10mb'}));app.use(morgan('dev'));
const base={name:{type:String,required:true,trim:true},slug:{type:String,trim:true},image:String,status:{type:String,default:'active'}};
const Category=mongoose.model('Category',new mongoose.Schema({...base,description:String,parent:String},{timestamps:true}));
const Brand=mongoose.model('Brand',new mongoose.Schema({...base,description:String},{timestamps:true}));
const Tag=mongoose.model('Tag',new mongoose.Schema({name:{type:String,required:true},slug:String},{timestamps:true}));
const Page=mongoose.model('Page',new mongoose.Schema({title:{type:String,required:true},slug:String,content:String,status:{type:String,default:'published'}},{timestamps:true}));
const Product=mongoose.model('Product',new mongoose.Schema({name:{type:String,required:true},slug:String,description:String,productType:{type:String,enum:['simple','variable'],default:'simple'},category:String,brand:String,tags:[String],price:{type:Number,required:true},comparePrice:Number,regularPrice:Number,salePrice:Number,stock:{type:Number,default:0},sku:String,image:String,images:[String],galleryImages:[String],badge:String,status:{type:String,default:'active'},attributes:{colors:[String],sizes:[String]},sizeVariations:[{size:String,regularPrice:Number,salePrice:Number,stock:Number}],variationImages:[{color:String,image:String}],linkedProducts:[String],sizeGuide:String,metaTitle:String,metaDescription:String},{timestamps:true}));
const Order=mongoose.model('Order',new mongoose.Schema({orderNumber:{type:String,required:true,unique:true},customer:String,email:String,phone:String,address:String,items:[mongoose.Schema.Types.Mixed],total:Number,status:{type:String,default:'Processing'},payment:String},{timestamps:true}));
const Contact=mongoose.model('Contact',new mongoose.Schema({name:String,email:String,phone:String,subject:String,message:String,status:{type:String,default:'new'}},{timestamps:true}));
const User=mongoose.model('User',new mongoose.Schema({name:String,email:{type:String,unique:true},password:String,role:{type:String,default:'admin'}},{timestamps:true}));
const Customer=mongoose.model('Customer',new mongoose.Schema({name:{type:String,trim:true},email:{type:String,required:true,unique:true,lowercase:true,trim:true},phone:String,password:{type:String,required:true},address:{line1:String,line2:String,city:String,province:String,postal:String}},{timestamps:true}));
let dbReady=false;
mongoose.connect(process.env.MONGODB_URI||'mongodb://127.0.0.1:27017/flairmantra').then(async()=>{dbReady=true;console.log('MongoDB connected');const starters=[{name:'FlairMantra Owner',email:'admin@flairmantra.in',role:'super-admin'},{name:'Store Manager',email:'manager@flairmantra.in',role:'store-manager'},{name:'Content Editor',email:'content@flairmantra.in',role:'content-editor'}];for(const seed of starters)if(!await User.findOne({email:seed.email}))await User.create({...seed,password:await bcrypt.hash('Flair@123',10)});}).catch(e=>console.warn('MongoDB unavailable — API running in demo mode:',e.message));
const fallback={products:[],categories:[]};
const auth=(req,res,next)=>{try{req.user=jwt.verify(req.headers.authorization?.replace('Bearer ',''),process.env.JWT_SECRET||'dev-secret');if(req.user.kind==='customer'||!req.user.role)throw 0;next()}catch{return res.status(401).json({message:'Unauthorized'})}};
app.get('/api/health',(req,res)=>res.json({ok:true,database:dbReady}));
app.get('/api/store',async(req,res)=>{if(!dbReady)return res.json(fallback);res.json({products:await Product.find({status:'active'}).sort({createdAt:-1}),categories:await Category.find({status:'active'}).sort({name:1})})});
// Customer accounts are separate from admin users so a shopper token can never reach /api/admin.
const customerToken=c=>jwt.sign({cid:c.id,kind:'customer'},process.env.JWT_SECRET||'dev-secret',{expiresIn:'30d'});
const customerView=c=>({id:c.id,name:c.name,email:c.email,phone:c.phone,address:c.address,createdAt:c.createdAt});
const customerAuth=(req,res,next)=>{try{const t=jwt.verify(req.headers.authorization?.replace('Bearer ',''),process.env.JWT_SECRET||'dev-secret');if(t.kind!=='customer')throw 0;req.customerId=t.cid;next()}catch{return res.status(401).json({message:'Please sign in again'})}};
const needDb=(req,res,next)=>dbReady?next():res.status(503).json({message:'Accounts are temporarily unavailable'});
app.post('/api/customers/register',needDb,async(req,res)=>{const {name,email,password,phone}=req.body||{};if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required'});if(String(password).length<8)return res.status(400).json({message:'Password must be at least 8 characters'});if(await Customer.findOne({email:String(email).toLowerCase().trim()}))return res.status(409).json({message:'An account with this email already exists'});const c=await Customer.create({name,email,phone,password:await bcrypt.hash(String(password),10)});res.status(201).json({token:customerToken(c),customer:customerView(c)})});
app.post('/api/customers/login',needDb,async(req,res)=>{const c=await Customer.findOne({email:String(req.body?.email||'').toLowerCase().trim()});if(!c||!await bcrypt.compare(String(req.body?.password||''),c.password))return res.status(401).json({message:'Incorrect email or password'});res.json({token:customerToken(c),customer:customerView(c)})});
app.put('/api/customers/me',needDb,customerAuth,async(req,res)=>{const {name,phone,address}=req.body||{};const c=await Customer.findByIdAndUpdate(req.customerId,{name,phone,address},{new:true});if(!c)return res.status(404).json({message:'Account not found'});res.json(customerView(c))});
app.get('/api/customers/orders',needDb,customerAuth,async(req,res)=>{const c=await Customer.findById(req.customerId);if(!c)return res.status(404).json({message:'Account not found'});res.json(await Order.find({email:c.email}).collation({locale:'en',strength:2}).sort({createdAt:-1}).limit(100))});
app.post('/api/orders',async(req,res)=>{if(!dbReady)return res.status(201).json({...req.body,demo:true});const order=await Order.create({orderNumber:req.body.id,customer:req.body.customer,email:req.body.email,phone:req.body.phone,address:req.body.address,items:req.body.items,total:req.body.total,status:req.body.status,payment:req.body.payment});res.status(201).json(order)});
app.post('/api/contact',async(req,res)=>{if(dbReady)await Contact.create(req.body);if(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS){const transport=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await transport.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to:'Pratixa13584@gmail.com',replyTo:req.body.email,subject:`FlairMantra enquiry: ${req.body.subject}`,text:`Name: ${req.body.name}\nEmail: ${req.body.email}\nPhone: ${req.body.phone}\n\n${req.body.message}`})}res.status(201).json({ok:true})});
app.post('/api/auth/login',async(req,res)=>{const u=dbReady?await User.findOne({email:req.body.email}):null;if(!u||!await bcrypt.compare(req.body.password,u.password))return res.status(401).json({message:'Invalid credentials'});res.json({token:jwt.sign({id:u.id,role:u.role},process.env.JWT_SECRET||'dev-secret',{expiresIn:'7d'}),user:{name:u.name,email:u.email}})});
const resources={products:Product,categories:Category,brands:Brand,tags:Tag,pages:Page,orders:Order,contacts:Contact};
for(const [path,Model] of Object.entries(resources)){app.get(`/api/admin/${path}`,auth,async(req,res)=>res.json(await Model.find().sort({createdAt:-1})));app.post(`/api/admin/${path}`,auth,async(req,res)=>res.status(201).json(await Model.create(req.body)));app.put(`/api/admin/${path}/:id`,auth,async(req,res)=>res.json(await Model.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true})));app.delete(`/api/admin/${path}/:id`,auth,async(req,res)=>{await Model.findByIdAndDelete(req.params.id);res.status(204).end()})}
const serverDir=path.dirname(fileURLToPath(import.meta.url));
const clientDist=['../../client/dist','../../frontend/dist'].map(p=>path.resolve(serverDir,p)).find(p=>fs.existsSync(p))||path.resolve(serverDir,'../../client/dist');
app.use(express.static(clientDist));
app.use('/api',(req,res)=>res.status(404).json({message:'Not found'}));
app.get('/{*splat}',(req,res)=>res.sendFile(path.join(clientDist,'index.html')));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:err.message||'Server error'})});
const port=process.env.PORT||5000;app.listen(port,()=>console.log(`FlairMantra API on http://localhost:${port}`));
